### ISSUE TITLE
Change the default snapshot name from "snapshot" to something else.

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/m2#125]
This snapshot already exists causes a lot of confusion to lot of users. If ceph is completely untouched it should still work, but sadly that may not be the case always. So we should probably have the default name changed to some UUID,

**Comment by naved001** [comment]
I poked around with this and had some discussions with @chemistry-sourabh. Here's what we can do:

1. Change the name to something simple, e.g., BMI-created-snapshot. So that way when it errors, it would read `BMI-created-snapshot already exists`. Easy to implement and understand.

2. We can give it some UUID. The problem with this is we need to track the name of the snapshot somehow because we would need it to remove it. We can do that with a database. And also when it errors, it would `<SUPER LONG UUID> does not exists` dont know how helpful would that be.

**Comment by naved001** [comment]
I need some answers here people @CCI-MOC/bmi-breakers

**Comment by naved001** [comment]
Fixed by #187. It is now configurable.
